class Controllers
	def self.all # list of user`s microcontrolles
		@@controllers_array
	end

	@@controllers_array = []
	def self.inherited(child_class) # hook when define class
		@@controllers_array << child_class if child_class.is_real_controller?
	end

	def self.is_real_controller?
		false
	end

	def self.print_cc_layout(position)
		if position == :before_main
			RubimCode.pout "/**************************************************************"
			RubimCode.pout " * This code was generated by RubimC micro-framework"
			RubimCode.pout " * RubimC version: #{RubimCode::VERSION}"
			RubimCode.pout " * Author: Evgeny Danilov"
			RubimCode.pout " * File created at #{Time.now}"
			RubimCode.pout " **************************************************************/"
			RubimCode.pout
			RubimCode.pout "#include <stdbool.h>"
			RubimCode.pout "#include <stdio.h>"
			RubimCode.pout
			yield if block_given?
			RubimCode.pout
			RubimCode.pout "int main(int argc, char *argv[]) {"
			RubimCode.level += 1
		else
			RubimCode.pout "return 1;"
			RubimCode.level -= 1
			RubimCode.pout "}"
		end
	end
end
