/**************************************************************
 * This code was generated by RubimC micro-framework
 * RubimC version: 0.1
 * Author: Evgeny Danilov
 * File created at 2016-04-28 23:19:38 +0300
 **************************************************************/

#include <stdbool.h>
#include <stdio.h>

#define __AVR_ATtiny13__ 1
#define F_CPU 1000000UL
#include <avr/io.h>
#include <avr/iotn13.h>
#include <avr/interrupt.h>

int main(int argc, char *argv[]) {
    int b, c, u1;
    int mas[3];
    int tim, mit;
