#!/bin/bash

# === preprocessing user program ===
ruby -e "require 'rubimc/preprocessor'" "$1" # $1 - compiled Ruby-file

# === extract filename without path and extention ===
FILENAME=$(basename "$1")
FILENAME="${FILENAME%.*}"

# === jump to 'release' folder ===
DIR=$(dirname "$1")
cd "${DIR}/release/"

# === generate C-code ===
ruby "${FILENAME}.rb" "${FILENAME}"
# ToDo: check exit status

# === compile C-code ===
gcc -o "${FILENAME}.out" "${FILENAME}.c" -std=c99 

# === execute user program ===
./"${FILENAME}.out"

