/**************************************************************
 * This code was generated by RubimC micro-framework
 * Include file for "/home/user/RubimCode/examples/release/ex1_avr_tiny13.c"
 **************************************************************/
int viar;
