/**************************************************************
 * This code was generated by RubimC micro-framework
 * RubimC version: 0.2.1
 * Author: Evgeny Danilov
 * File created at 2016-05-03 18:30:27 +0300
 **************************************************************/

#include <stdbool.h>
#include <stdio.h>
#include "ex1_avr_tiny13.h"

#define __AVR_ATtiny13__ 1
#define F_CPU 1000000UL
#include <avr/io.h>
#include <avr/iotn13.h>
#include <avr/interrupt.h>


int main(int argc, char *argv[]) {
    viar = (12);
    
    // Init ADC
    ADMUX = (0<<REFS0) | (0<<ADLAR) | (0b00<<MUX0);
    ADCSRA = (1<<ADEN) | (0<<ADATE) | (1<<ADPS0) | (0<<ADIE);
    
    ADMUX |= 1<<ADIE;
    viar = (123);
    
    // === Main Infinite Loop === //
    while (true) {
        int qwe;
        qwe = (12);
    } // end main loop
    
    return 1;
}

// ADC Interrupt
ISR(ADC_vect) {
    int __rubim__volt = ADCL + ((ADCH&0b11) << 8);
    DDRB |= 1<<(3);
    if ((__rubim__volt<(30))) {
        PORTB &= ~(1<<(3));
        }
    if ((__rubim__volt>=(220))) {
        PORTB |= 1<<(3);
        }
}
