/**************************************************************
 * This code was generated by RubimC micro-framework
 * Include file for "/home/user/RubimCode/examples/release/ex2_raw_code.c"
 **************************************************************/
