/**************************************************************
 * This code was generated by RubimC micro-framework
 * RubimC version: 0.2.1
 * RubimC author: Evgeny Danilov
 * File created at 2016-05-07 13:55:27 +0300
 **************************************************************/

#include <stdbool.h>
#include <stdio.h>


#include "ex2_raw_code.h"

int main(int argc, char *argv[]) {
    // This is clear C code, it can be compiled with 'gcc' utility
    printf("========Run Program========\n");
    printf("Hello! I`m code generated by RubimC and compiled by gcc\n");
    printf("I have %d arguments: ", (argc));
    for (int i1=0; i1<(argc); i1++) {
        printf("%s ", (argv[i1]));
        }
    printf("\n");
    int b;
    bool c;
    double u1;
    b = (1);
    c = (false);
    u1 = (b+(c*(b))+(2*(b)));
    int __rubim__rval1 = 0;
    if ((b)) {
        int __rubim__rval2 = 0;
        if ((c==(u1))) {
            b = (c+(27));
            if ((b!=(c))) {
                u1 = (33);
                }
            }
        __rubim__rval1 = (__rubim__rval2);
        }
    for (int i1=0; i1<(u1); i1++) {
        printf("now 'i' value is %d\n", i1);
        }
    
    return 1;
}
