#####################################################################
# Example: "Clear-C code"                                         	#
# Author: Evgeny Danilov                                        	#
# Created at 2016-04-26                                         	#
#####################################################################

require 'rubimc'

def main(argv)
	print_comment "This is clear C code, it can be compiled with 'gcc' utility"
	printf "========Run Program========\n"
	printf "Hello! I`m code generated by RubimC and compiled by gcc\n"
	printf "I have %d arguments: ", argv.count
	argv.count.times do |i|
		printf "%s ", argv[i]
	end
	printf "\n"

	b = integer :b
	c = boolean :c
	u1 = double :u1
	b .c_assign=  RubimCode::UserVariable.new(1, 'fixed'); c .c_assign= RubimCode::UserVariable.new(false, 'fixed')
	u1 .c_assign= b + c*b + ( RubimCode::UserVariable.new(2, 'fixed')*b)

	RubimCode.rubim_if b do
		RubimCode.rubim_if c==u1 do
			b .c_assign= c +  RubimCode::UserVariable.new(27, 'fixed')
			u1 .c_assign=  RubimCode::UserVariable.new(33, 'fixed') if RubimCode.rubim_ifmod b!= c; RubimCode.rubim_end;
		end 
	end

	u1.times do |i|
		printf("now 'i' value is %d\n", i)
	end
end