#####################################################################
# Example: "Clear-C code"                                         	#
# Author: Evgeny Danilov                                        	#
# Created at 2016-04-26                                         	#
#####################################################################

require 'rubimc'

def main(argv)
	print_comment "This is clear C code, it can be compiled with 'gcc' utility"
	printf "========Run Program========\n"
	printf "Hello! I`m code generated by RubimC and compiled by gcc\n"
	printf "I have %d arguments: ", argv.count
	argv.count.times do |i|
		printf "%s ", argv[i]
	end
	printf "\n"

	integer :b, :c, :u1
	b = 1; c = 2
	u1 = b + c*b + (2*b)

	if b
		if c==u1
			b = c + 27
			u1 = 33 if b!= c
		end 
	end

	u1.times do |i|
		printf("now 'i' value is %d\n", i)
	end
end